name: FUELD.
favicon: null
layout_spectrum: 0.2636
typography_spectrum: 0.00594
title: Food for fitness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#2b2b2b'
    - '#ad7b66'
    - '#ead8b3'
  brandStrength: 0.875
  lightness: 0.4144972749054432
  saturation: 0.0625
  rhythmicContrast: 0.7886734565254301
purpose: []
